### ISSUE TITLE
Review Level previews

### ISSUE THREAD

**Issue by Mikotey** [Saplings-Projects/Birthday-2024#120]
![image](https://github.com/Saplings-Projects/Birthday-2024/assets/9286524/facd591d-a554-403e-9542-7d63c917ff44)
![image](https://github.com/Saplings-Projects/Birthday-2024/assets/9286524/57fea468-9ac7-4962-8938-9ce8de986bf4)

Noticed some of the level previews are repeats. They might need to be reviewed to make sure they've been assigned correctly or need new previews

**Comment by Casulono** [comment]
These are the only ones that have been mixed but I've noticed that many previews are too big even after scaling to be shown in full. I'll be working on scaling them

**Comment by Mikotey** [comment]
So is this task still active or do you have more changes to make?

**Comment by Casulono** [comment]
Going back to https://github.com/Saplings-Projects/Birthday-2024/pull/125 I've included an idea and one scaled level as a showcase. Not all previews are properly shown in buttons because levels are rectangular while buttons are square. If you think we should have them changed then I can go and scale all images to the same size so they will be shown properly. However, they will be stretched in Y axis

**Comment by Mikotey** [comment]
![image](https://github.com/Saplings-Projects/Birthday-2024/assets/9286524/175d8015-37d2-4799-b9fa-d04d35e9c289)

Ah, I see it now. I think it's better the previous way. While it does clip the sides, it doesn't distort the image.
While it would be cool to see the full view of the level, they are just previews. They can see the level proper when they open it. Then it would have the blockers in place as well.
